# Project Name
TARGET = ReverbExample

# Sources
CPP_SOURCES = ReverbExample.cpp \

# Library Locations
LIBDAISY_DIR = ../../libdaisy/
DAISYSP_DIR = ../../daisysp/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
