# Project Name
TARGET = ex_patch_verb

# Sources
CPP_SOURCES = ex_verb.cpp

# Library Locations
LIBDAISY_DIR = ../../../../libdaisy
DAISYSP_DIR = ../../../../daisysp

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = ../../../../core
include $(SYSTEM_FILES_DIR)/Makefile

