# Project Name
TARGET = QSPI

# Sources
CPP_SOURCES = QSPI.cpp

# I believe most of the tests are optimized out with
# the default flag
OPT = -O0

# Library Locations
LIBDAISY_DIR = ../../libdaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

