# Project Name
TARGET = adenv

# Sources
CPP_SOURCES = adenv.cpp

# Library Locations
DAISYSP_DIR ?= ../../../DaisySP
LIBDAISY_DIR ?= ../../../libDaisy

# Core location, and generic Makefile.
# Overwrite LIBDAISY Environment variable to the location of the lib on your machine.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

