/* Generated by Edge Impulse
    *
    * Permission is hereby granted, free of charge, to any person obtaining a copy
    * of this software and associated documentation files (the "Software"), to deal
    * in the Software without restriction, including without limitation the rights
    * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    * copies of the Software, and to permit persons to whom the Software is
    * furnished to do so, subject to the following conditions:
    *
    * The above copyright notice and this permission notice shall be included in
    * all copies or substantial portions of the Software.
    *
    * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    * SOFTWARE.
    */

    #ifndef _EI_CLASSIFIER_TFLITE_RESOLVER_H_
    #define _EI_CLASSIFIER_TFLITE_RESOLVER_H_

    #include "edge-impulse-sdk/tensorflow/lite/micro/kernels/micro_ops.h"
    
#define EI_TFLITE_RESOLVER static tflite::MicroMutableOpResolver<4> resolver; \
    resolver.AddConv2D(); \
    resolver.AddFullyConnected(); \
    resolver.AddReshape(); \
    resolver.AddExpandDims();

#endif // _EI_CLASSIFIER_TFLITE_RESOLVER_H_
