# Project Name
TARGET = ex_field_keyboard_test

# Sources
CPP_SOURCES = KeyboardTest.cpp

# Library Locations
LIBDAISY_DIR = ../../../../libdaisy
DAISYSP_DIR = ../../../../daisysp

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = ../../../../core
include $(SYSTEM_FILES_DIR)/Makefile

