# Project Name
TARGET = Template

# Sources
CPP_SOURCES = Template.cpp

# Library Locations
LIBDAISY_DIR = @LIBDAISY_DIR@
DAISYSP_DIR = @DAISYSP_DIR@

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
