# Project Name
TARGET = bytebeat

# Use LGPL version of DaisySP (optional, set to 1 if needed)
USE_DAISYSP_LGPL=1

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core

# Source files
# CPP_SOURCES = bytebeat.cpp
CPP_SOURCES = bytebeat.cpp bytebeat_synth.cpp

# Include the Daisy system Makefile
include $(SYSTEM_FILES_DIR)/Makefile






