# Project Name
TARGET = Blink

# Sources
CPP_SOURCES = Blink.cpp \
lut.cpp \

C_INCLUDES += -I. \

# Library Locations
LIBDAISY_DIR = ../../libdaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

