# Project Name
TARGET = HachiKit

# Sources
CPP_SOURCES += HachiKit.cpp \
Screen.cpp \
Bd8.cpp \
Sd8.cpp \
SdNoise.cpp \
FmDrum.cpp \
HhSource68.cpp \
Ch.cpp \
AhdEnv.cpp \
Oh.cpp \
Cy.cpp \
Cow8.cpp \
Tom.cpp \
ClickSource.cpp


OPT = -Os

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

